name: Build Encore Zip

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
      - 'module/**'
      - 'webui/**'
      - 'gamelist.txt'
      - 'version'

jobs:
  build:
    name: Build Flashable Zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: NDK Setup
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: r27b
    - name: Build encore-service JNI
      working-directory: ./src
      run: ndk-build
    - name: Build WebUI
      working-directory: ./src/webui
      run: |
        npm install
        npm run tailwind
        npm run build
        cp ./dist/* ../../module/webroot
    - name: Compile flashable zip
      id: compileZip
      run: |
        cp -r ./src/libs ./module
        cp -r ./src/scripts/* ./module/system/bin
        cp LICENSE ./module
        bash ./gamelist_compile.sh
        version="$(cat ./version)"
        version_code=$(git rev-list HEAD --count)
        gitsha1=$(git rev-parse --short HEAD)
        sed -i "s/version=.*/version=$version (GIT@$gitsha1)/" ./module/module.prop
        sed -i "s/versionCode=.*/versionCode=$version_code/" ./module/module.prop
        zipName="encore-$version-$version_code_$gitsha1.zip" && echo "zipName=$zipName" >> $GITHUB_OUTPUT
        cd ./module && zip -r9 ../$zipName * -x *placeholder *.map
    - name: Upload to telegram
      env:
        CHAT_ID: ${{ secrets.CHAT_ID }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        TITLE: Encore Tweaks
      run: |
        if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
          export VERSION=$(git rev-list --count HEAD)
          bash $GITHUB_WORKSPACE/.github/scripts/telegram_bot.sh $GITHUB_WORKSPACE/${{ steps.compileZip.outputs.zipName }}
        else
          echo "Telegram bot token is undefined, please add it to repository secrets!"
          exit 1
        fi
