name: Scripts checkup

on:
  push:
    paths:
      - '.github/scripts/**'
      - 'scripts/**'
      - 'module/**'

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: |
          wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
          sudo mv shellcheck-stable/shellcheck /usr/local/bin/
          sudo chmod +x /usr/local/bin/shellcheck

      - name: Check shell scripts
        run: |
          shellcheck .github/scripts/*.sh scripts/** module/*.sh
